imports:
    - { resource: ../../config/parameters.yml }
    - { resource: ../../config/security.yml }

    # Mopa Bootstrap
    - { resource: ../../config//mopa/mopa_bootstrap.yml }

    # Knp Paginator
    - { resource: ../../config/knp/knp_paginator.yml }

# Assetic Configuration
#assetic:
#    debug:          %kernel.debug%
#    use_controller: false
#    filters:
#        cssrewrite: ~
#        # closure:
#        #     jar: %kernel.root_dir%/java/compiler.jar
#        # yui_css:
#        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar
#
#        # Comment out those lines if you wish to use the less version of bootstrap
#        less:
#            node: /usr/local/bin/node
#            node_paths: [/usr/local/node/node-v0.10.22/lib/node_modules]
#            apply_to: "\.less$"