NelmioApiDocBundle:
    resource:     "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:       /api/doc

sonata_api_news:
    type:         rest
    prefix:       /api/news
    resource:     "@SonataNewsBundle/Resources/config/routing/api.xml"

sonata_api_media:
    type:         rest
    prefix:       /api/media
    resource:     "@SonataMediaBundle/Resources/config/routing/api.xml"

sonata_api_notification:
    type:         rest
    prefix:       /api/notification
    resource:     "@SonataNotificationBundle/Resources/config/routing/api.xml"